"""Change seller_id to Integer

Revision ID: 05c0635f9c1a
Revises: edee7cf6dcd4
Create Date: 2025-11-07 09:13:25.237822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c0635f9c1a'
down_revision = 'edee7cf6dcd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('meeting_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('seller_id',
               existing_type=sa.String(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['seller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('seller_id',
               existing_type=sa.Integer(),
               type_=sa.String(),
               existing_nullable=True)

    op.drop_table('reminder')
    # ### end Alembic commands ###
