"""add new coloums in product table seller_id  and seller

Revision ID: edee7cf6dcd4
Revises: 3061668e15e8
Create Date: 2025-10-31 09:56:55.573816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edee7cf6dcd4'
down_revision = '3061668e15e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('seller_id',
               existing_type=sa.String(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['seller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('seller_id',
               existing_type=sa.Integer(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###
